# This is My first Dockerfile
# Version 1.0
# Author:ZHEN

#Base images
FROM centos

#MAINTAINER
MAINTAINER ZHEN

#ADD
ADD pcre2-10.20.tar.gz /usr/local/src
ADD nginx-1.11.3.tar.gz /usr/local/src

#RUN
RUN yum install -y wget gcc gcc-c++ make openssl-devel
RUN useradd -s /sbin/nologin -M wwww

#WORKDIR
WORKDIR /usr/local/src/nginx-1.11.3
RUN ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module  --with-http_stub_status_module --with-pcre=/usr/local/src/pcre2-10.20 && make && make install

RUN echo "daemo off;" >> /usr/local/nginx/conf/nginx.conf

ENV PATH /usr/local/nginx/sbin:$PATH
EXPOSE 80

CMD  ["nginx"]
